# Generated by Django 6.0.1 on 2026-02-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='chapter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
