# Generated by Django 6.0.1 on 2026-03-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='finish_date',
            field=models.DateTimeField(null=True),
        ),
    ]
