# Generated by Django 6.0.1 on 2026-05-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_finish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='finish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
