# Generated by Django 6.0.1 on 2026-05-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_finish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
